/*
 * @title Generate Icon SCSS
 * @description A module that will convert an svg icon code into a scss class
 */


/*********************************************************************************
 1. DEPENDENCIES
 *********************************************************************************/

import configIconfont from '../../config/iconfont.js';
import data from 'gulp-data';
import rename from 'gulp-rename';
import swig from 'gulp-swig';


/*********************************************************************************
 2. EXPORTS
 *********************************************************************************/

module.exports = codepoints => {
  const scssTemplate = '/_iconfont.scss.swig';
  return gulp
    .src(`${__dirname}${scssTemplate}`)
    .pipe(plumber({errorHandler: sharedEvents.onError}))
    .pipe(data(function () {
      return {
        icons: codepoints.map(icon => {
          return {
            name: icon.name,
            code: icon.codepoint.toString(16)
          }
        }),
        className: configIconfont.name,
        fontName: configIconfont.name,
        fontPath: '../fonts/',
        comment: '// Custom icon font\n// Font and SCSS generated by gulp - do not edit directly'
      }
    }))
    .pipe(swig())
    .pipe(rename(scssTemplate.replace('.swig', '')))
    .pipe(gulp.dest(`${ sharedPaths.srcDir }/sass/components/`));
};
