/*
 * @title Generate Icon SCSS
 * @description A module that will convert an svg icon code into a scss class
 */


/*********************************************************************************
 1. DEPENDENCIES
 *********************************************************************************/

import sharedPaths    from '../../shared/paths.js';
import sharedEvents   from '../../shared/events.js';
import configIconfont from '../../config/iconfont.conf.js';
import gulp           from 'gulp';
import data           from 'gulp-data';
import plumber        from 'gulp-plumber';
import rename         from 'gulp-rename';
import swig           from 'gulp-swig';

/*********************************************************************************
 2. EXPORTS
 *********************************************************************************/

export default codepoints => {
    let scssTemplate = '/_iconfont.scss.swig';
    return gulp
        .src(`${__dirname}${scssTemplate}`)
        .pipe(plumber({errorHandler: sharedEvents.onError}))
        .pipe(data(() => {
            return {
                icons: codepoints.map(glyph => {
                    return {
                        name: glyph.name,
                        code: glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase()
                    };
                }),
                className: configIconfont.name,
                fontName: configIconfont.name,
                fontPath: '../fonts/',
                comment: '// Custom icon font\n// Font and SCSS generated by gulp - do not edit directly'
            };
        }))
        .pipe(swig())
        .pipe(rename(scssTemplate.replace('.swig', '')))
        .pipe(gulp.dest(`${ sharedPaths.srcDir }/sass/components/`));
};
